Hello, my name is ***Heather*** and I am from Hamilton, Ontario, Canada! I recently graduated with an Honours Bachelor of Science from the Integrated Science program at McMaster University with a biology concentration. I am an MSc student in the Department of Geograpghy working under the supervision of Dr. Simon Donner. I will be pursuing research on climate change and the impact that it has on coral reef biomes. 

### Research Experience:memo:
During my undergraduate degree I had the opportunity to participate in a variety of field courses ranging from
studying the unique geology and environment of Iceland, to the health of the coral reefs in the Caribbean, to the geology and hydrology of the karstic landscape in the Yucatán Peninsula, Mexico. During the summers of 2015 and 2016 I completed marine field research projects under the Operation Wallacea program where I learned about marine biodiversity and conservation management strategies. This past summer I worked as part of the Educational and Supervisory Science Staff for Operation Wallacea where I delivered reef ecology lectures and in-water practicals for high school and university students taking the reef ecology course on the Utila marine site in Honduras.

### Interests Outside School
- Scuba diving :ocean: (currently a __PADI Divemaster!__) 
- Canoe camping :tent:
- Hiking :sunrise_over_mountains:
- Cycling :bicyclist: 
- Running :runner: 
- Swimming :swimmer:
- Skiing :ski:
- Spending time with friends and family :family: 

### Places I Have Visited:airplane::earth_americas:
- Bahamas
- Belgium
- Cuba
- France
- Iceland
- Mexico
- United States
    - Arizona
    - California
    - Florida
    - Maine
    - Michigan
    - New York
    - South Carolina

## Favourite Quote :speech_balloon:

> "The sea, once it casts its spell, holds one in its net of wonder forever."
>
> Jacques Yves Cousteau
